config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :new, :create, :destroy]do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
    #  creates a new List (FAILED - 4)
    #   assigns a newly created list as @list (FAILED - 5)
    #   redirects to the created list (FAILED - 6)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6 ">
      <%= simple_form_for [@list, @bookmark] do |t| %>
        <%= t.association :movie %>
        <%= t.input :comment %>
        <%= t.submit class: 'btn btn-primary mt-3'%>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1>Select your movie-style</h1>
  <div class="row">
    <% @lists.each do|list| %>
      <div class="card1 col-12 col-md-6 col-lg-4 card-size gap-1 my-4">
        <%= link_to list.name.capitalize, list_path(list), class: 'list-name'%>
        <%= link_to list_path(list),
  method: :delete, class: 'delete-list',
  data: { confirm: "delete #{list.name.capitalize}}?"} do%>
          <i class="fas fa-times"></i>
        <% end %>
        <div class="card-body perso-card" style="background-image: url(<%= list.photo.attached? ?
            cl_image_path(list.photo.key) : image_path('https://img-19.ccm2.net/HBieDLy0LheYz2zkrl2JbG9Brm4=/1000x420/smart/6246fc94bad94dda9c611a1fdc87dd76/ccmcms-commentcamarche/23887428.jpg') %>)">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 box">
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.submit class: 'btn btn-primary mt-3'%>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1>Your selected list</h1>
  <h2 class=' pt-2'><%= @list.name.capitalize %></h2>
  <div>
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card-show">
        <div class="d-flex justify-content-center">
          <%= image_tag bookmark.movie.poster_url, width: '200px', class: 'show-image ' %>
        </div>
        <div class='p-2 pb-5'>
          <h2 class='mb-2'><%= bookmark.movie.title %></h2>
          <p ><%= bookmark.movie.overview %></p>
          <%= link_to "Delete this bookmark", bookmark_path(bookmark), method: :delete, class: 'btn btn-danger absolute1', data: { confirm: "delete #{bookmark.movie.title}?"} %>
          <p>Comments:</p>
          <p><%= bookmark.comment.capitalize %></p>
        </div>
        <%# <li><%= link_to 'Add a rating to this movie list', </li> %>
      </div>
    <% end %>
  </div >
  <%= link_to "Add a bookmark", new_list_bookmark_path(@list), class: 'btn-lg btn-info margin-bot' %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-image: url(https://deadline.com/wp-content/uploads/2021/05/Hollywood-Sign.jpg?w=681&h=383&crop=1);">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/lists">Your lists</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/lists/new">New list</a>
      </li>
    </ul>
  </div>
</div>